/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CatalogGroupId } from './catalog-group-id';
import { CatalogId } from './catalog-id';
import { CatalogItemId } from './catalog-item-id';
 /**
 * 
 *
 * @export
 * @interface AddCatalogItemCommand
 */
export interface AddCatalogItemCommand {

    /**
     * @type {CatalogItemId}
     * @memberof AddCatalogItemCommand
     */
    catalogItemId?: CatalogItemId;

    /**
     * @type {CatalogId}
     * @memberof AddCatalogItemCommand
     */
    catalogId?: CatalogId;

    /**
     * @type {CatalogGroupId}
     * @memberof AddCatalogItemCommand
     */
    catalogGroupId?: CatalogGroupId;

    /**
     * @type {string}
     * @memberof AddCatalogItemCommand
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof AddCatalogItemCommand
     */
    description?: string | null;
}
