/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AddressDTO
 */
export interface AddressDTO {

    /**
     * @type {string}
     * @memberof AddressDTO
     */
    name1?: string | null;

    /**
     * @type {string}
     * @memberof AddressDTO
     */
    name2?: string | null;

    /**
     * @type {string}
     * @memberof AddressDTO
     */
    street?: string | null;

    /**
     * @type {string}
     * @memberof AddressDTO
     */
    houseNumber?: string | null;

    /**
     * @type {string}
     * @memberof AddressDTO
     */
    postalCode?: string | null;

    /**
     * @type {string}
     * @memberof AddressDTO
     */
    city?: string | null;

    /**
     * @type {string}
     * @memberof AddressDTO
     */
    country?: string | null;

    /**
     * @type {string}
     * @memberof AddressDTO
     */
    displayName?: string | null;
}
