/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CatalogItemNumber
 */
export interface CatalogItemNumber {

    /**
     * @type {number}
     * @memberof CatalogItemNumber
     */
    value?: number;

    /**
     * @type {boolean}
     * @memberof CatalogItemNumber
     */
    isTemporary?: boolean;

    /**
     * @type {string}
     * @memberof CatalogItemNumber
     */
    long?: string | null;

    /**
     * @type {string}
     * @memberof CatalogItemNumber
     */
    shortForm?: string | null;

    /**
     * @type {number}
     * @memberof CatalogItemNumber
     */
    digits?: number;
}
