/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CatalogGroupDTO } from './catalog-group-dto';
import { CatalogId } from './catalog-id';
 /**
 * 
 *
 * @export
 * @interface CatalogDTO
 */
export interface CatalogDTO {

    /**
     * @type {CatalogId}
     * @memberof CatalogDTO
     */
    id?: CatalogId;

    /**
     * @type {string}
     * @memberof CatalogDTO
     */
    name?: string | null;

    /**
     * @type {Array<CatalogGroupDTO>}
     * @memberof CatalogDTO
     */
    groups?: Array<CatalogGroupDTO> | null;

    /**
     * @type {string}
     * @memberof CatalogDTO
     */
    displayName?: string | null;
}
