/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CatalogGroupId } from './catalog-group-id';
import { CatalogId } from './catalog-id';
import { CatalogItemDTO } from './catalog-item-dto';
 /**
 * 
 *
 * @export
 * @interface CatalogGroupDTO
 */
export interface CatalogGroupDTO {

    /**
     * @type {CatalogGroupId}
     * @memberof CatalogGroupDTO
     */
    id?: CatalogGroupId;

    /**
     * @type {CatalogId}
     * @memberof CatalogGroupDTO
     */
    catalogId?: CatalogId;

    /**
     * @type {string}
     * @memberof CatalogGroupDTO
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof CatalogGroupDTO
     */
    description?: string | null;

    /**
     * @type {Array<CatalogItemDTO>}
     * @memberof CatalogGroupDTO
     */
    items?: Array<CatalogItemDTO> | null;

    /**
     * @type {string}
     * @memberof CatalogGroupDTO
     */
    displayName?: string | null;
}
