/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CatalogGroupId } from './catalog-group-id';
import { CatalogId } from './catalog-id';
import { CatalogItemId } from './catalog-item-id';
import { CatalogItemNumber } from './catalog-item-number';
import { CatalogItemPrice } from './catalog-item-price';
import { Currency } from './currency';
import { CustomerCatalogItemPrice } from './customer-catalog-item-price';
import { Unit } from './unit';
 /**
 * 
 *
 * @export
 * @interface CatalogItemDTO
 */
export interface CatalogItemDTO {

    /**
     * @type {CatalogItemId}
     * @memberof CatalogItemDTO
     */
    id?: CatalogItemId;

    /**
     * @type {CatalogGroupId}
     * @memberof CatalogItemDTO
     */
    catalogGroupId?: CatalogGroupId;

    /**
     * @type {CatalogId}
     * @memberof CatalogItemDTO
     */
    catalogId?: CatalogId;

    /**
     * @type {CatalogItemNumber}
     * @memberof CatalogItemDTO
     */
    number?: CatalogItemNumber;

    /**
     * @type {string}
     * @memberof CatalogItemDTO
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof CatalogItemDTO
     */
    description?: string | null;

    /**
     * @type {boolean}
     * @memberof CatalogItemDTO
     */
    isActive?: boolean;

    /**
     * @type {string}
     * @memberof CatalogItemDTO
     */
    groupName?: string | null;

    /**
     * @type {Array<CatalogItemPrice>}
     * @memberof CatalogItemDTO
     */
    prices?: Array<CatalogItemPrice> | null;

    /**
     * @type {Array<CustomerCatalogItemPrice>}
     * @memberof CatalogItemDTO
     */
    customerPrices?: Array<CustomerCatalogItemPrice> | null;

    /**
     * @type {Unit}
     * @memberof CatalogItemDTO
     */
    unit?: Unit;

    /**
     * @type {CatalogItemPrice}
     * @memberof CatalogItemDTO
     */
    currentPrice?: CatalogItemPrice;

    /**
     * @type {string}
     * @memberof CatalogItemDTO
     */
    displayName?: string | null;

    /**
     * @type {Currency}
     * @memberof CatalogItemDTO
     */
    currency?: Currency;
}
