/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CatalogItemId } from './catalog-item-id';
import { CatalogItemNumber } from './catalog-item-number';
import { CatalogItemPrice } from './catalog-item-price';
import { Unit } from './unit';
 /**
 * 
 *
 * @export
 * @interface CatalogItemDTO
 */
export interface CatalogItemDTO {

    /**
     * @type {CatalogItemId}
     * @memberof CatalogItemDTO
     */
    id?: CatalogItemId;

    /**
     * @type {CatalogItemNumber}
     * @memberof CatalogItemDTO
     */
    number?: CatalogItemNumber;

    /**
     * @type {string}
     * @memberof CatalogItemDTO
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof CatalogItemDTO
     */
    description?: string | null;

    /**
     * @type {Array<CatalogItemPrice>}
     * @memberof CatalogItemDTO
     */
    prices?: Array<CatalogItemPrice> | null;

    /**
     * @type {{ [key: string]: CatalogItemPrice; }}
     * @memberof CatalogItemDTO
     */
    customerPrices?: { [key: string]: CatalogItemPrice; } | null;

    /**
     * @type {Unit}
     * @memberof CatalogItemDTO
     */
    unit?: Unit;

    /**
     * @type {CatalogItemPrice}
     * @memberof CatalogItemDTO
     */
    catalogItemPrice?: CatalogItemPrice;

    /**
     * @type {string}
     * @memberof CatalogItemDTO
     */
    displayName?: string | null;
}
