/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CommunicationDTO
 */
export interface CommunicationDTO {

    /**
     * @type {string}
     * @memberof CommunicationDTO
     */
    email?: string | null;

    /**
     * @type {string}
     * @memberof CommunicationDTO
     */
    mobil?: string | null;

    /**
     * @type {string}
     * @memberof CommunicationDTO
     */
    phone?: string | null;

    /**
     * @type {string}
     * @memberof CommunicationDTO
     */
    website?: string | null;

    /**
     * @type {string}
     * @memberof CommunicationDTO
     */
    displayName?: string | null;
}
