/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PaymentId } from './payment-id';
 /**
 * 
 *
 * @export
 * @interface CompletePaymentCommand
 */
export interface CompletePaymentCommand {

    /**
     * @type {PaymentId}
     * @memberof CompletePaymentCommand
     */
    id?: PaymentId;

    /**
     * @type {number}
     * @memberof CompletePaymentCommand
     */
    amount?: number;

    /**
     * @type {Date}
     * @memberof CompletePaymentCommand
     */
    paidAt?: Date;
}
