/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Color } from './color';
import { FileReference } from './file-reference';
 /**
 * 
 *
 * @export
 * @interface CorporateDesign
 */
export interface CorporateDesign {

    /**
     * @type {string}
     * @memberof CorporateDesign
     */
    brand?: string | null;

    /**
     * @type {string}
     * @memberof CorporateDesign
     */
    shortName?: string | null;

    /**
     * @type {string}
     * @memberof CorporateDesign
     */
    slogan?: string | null;

    /**
     * @type {Color}
     * @memberof CorporateDesign
     */
    color1?: Color;

    /**
     * @type {Color}
     * @memberof CorporateDesign
     */
    color2?: Color;

    /**
     * @type {FileReference}
     * @memberof CorporateDesign
     */
    logo?: FileReference;
}
