/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Currency } from './currency';
import { CustomerId } from './customer-id';
import { DatePeriod } from './date-period';
import { InvoiceId } from './invoice-id';
import { OfferId } from './offer-id';
import { OrderId } from './order-id';
import { TaxRate } from './tax-rate';
 /**
 * 
 *
 * @export
 * @interface CreateInvoiceCommand
 */
export interface CreateInvoiceCommand {

    /**
     * @type {InvoiceId}
     * @memberof CreateInvoiceCommand
     */
    id: InvoiceId;

    /**
     * @type {CustomerId}
     * @memberof CreateInvoiceCommand
     */
    customerId: CustomerId;

    /**
     * @type {CustomerInvoiceIdId}
     * @memberof CreateInvoiceCommand
     */
    templateId?: InvoiceId;

    /**
     * @type {number}
     * @memberof CreateInvoiceCommand
     */
    fiscalYear: number;

    /**
     * @type {Currency}
     * @memberof CreateInvoiceCommand
     */
    currency: Currency;

    /**
     * @type {DatePeriod}
     * @memberof CreateInvoiceCommand
     */
    performancePeriod?: DatePeriod;

    /**
     * @type {TaxRate}
     * @memberof CreateInvoiceCommand
     */
    taxRate?: TaxRate;

    /**
     * @type {OrderId}
     * @memberof CreateInvoiceCommand
     */
    orderId?: OrderId;

    /**
     * @type {OfferId}
     * @memberof CreateInvoiceCommand
     */
    offerId?: OfferId;
}
