/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AddressDTO } from './address-dto';
import { CommunicationDTO } from './communication-dto';
import { CorporateDesign } from './corporate-design';
import { Currency } from './currency';
import { CustomerId } from './customer-id';
import { CustomerNumber } from './customer-number';
 /**
 * 
 *
 * @export
 * @interface CustomerDTO
 */
export interface CustomerDTO {

    /**
     * @type {string}
     * @memberof CustomerDTO
     */
    displayName?: string | null;

    /**
     * @type {CustomerId}
     * @memberof CustomerDTO
     */
    id?: CustomerId;

    /**
     * @type {CustomerNumber}
     * @memberof CustomerDTO
     */
    number?: CustomerNumber;

    /**
     * @type {string}
     * @memberof CustomerDTO
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof CustomerDTO
     */
    industryBranch?: string | null;

    /**
     * @type {Currency}
     * @memberof CustomerDTO
     */
    currency?: Currency;

    /**
     * @type {AddressDTO}
     * @memberof CustomerDTO
     */
    mainAddress?: AddressDTO;

    /**
     * @type {CommunicationDTO}
     * @memberof CustomerDTO
     */
    communication?: CommunicationDTO;

    /**
     * @type {CorporateDesign}
     * @memberof CustomerDTO
     */
    corporateDesign?: CorporateDesign;
}
