/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Currency } from './currency';
import { CustomerId } from './customer-id';
 /**
 * 
 *
 * @export
 * @interface CustomerCatalogItemPrice
 */
export interface CustomerCatalogItemPrice {

    /**
     * @type {number}
     * @memberof CustomerCatalogItemPrice
     */
    price?: number;

    /**
     * @type {Currency}
     * @memberof CustomerCatalogItemPrice
     */
    currency?: Currency;

    /**
     * @type {Date}
     * @memberof CustomerCatalogItemPrice
     */
    validFrom?: Date;

    /**
     * @type {CustomerId}
     * @memberof CustomerCatalogItemPrice
     */
    customerId?: CustomerId;
}
