/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DatePeriod
 */
export interface DatePeriod {

    /**
     * @type {string}
     * @memberof DatePeriod
     */
    from?: string;

    /**
     * @type {string}
     * @memberof DatePeriod
     */
    to?: string | null;
}
