/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FileReference
 */
export interface FileReference {

    /**
     * @type {string}
     * @memberof FileReference
     */
    fileName?: string | null;

    /**
     * @type {string}
     * @memberof FileReference
     */
    fileUrl?: string | null;

    /**
     * @type {string}
     * @memberof FileReference
     */
    fileId?: string | null;

    /**
     * @type {Date}
     * @memberof FileReference
     */
    uploadedAt?: Date;
}
