/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Currency } from './currency';
import { TopItem } from './top-item';
 /**
 * 
 *
 * @export
 * @interface GetSalesDashboardReadModel
 */
export interface GetSalesDashboardReadModel {

    /**
     * @type {number}
     * @memberof GetSalesDashboardReadModel
     */
    thisYear?: number;

    /**
     * @type {number}
     * @memberof GetSalesDashboardReadModel
     */
    lastYear?: number;

    /**
     * @type {Currency}
     * @memberof GetSalesDashboardReadModel
     */
    currency?: Currency;

    /**
     * @type {Array<TopItem>}
     * @memberof GetSalesDashboardReadModel
     */
    top3InvoicesEver?: Array<TopItem> | null;

    /**
     * @type {Array<TopItem>}
     * @memberof GetSalesDashboardReadModel
     */
    top3CustomersEver?: Array<TopItem> | null;

    /**
     * @type {Array<TopItem>}
     * @memberof GetSalesDashboardReadModel
     */
    top3CustomersThisYear?: Array<TopItem> | null;

    /**
     * @type {Array<TopItem>}
     * @memberof GetSalesDashboardReadModel
     */
    top3CustomersLastYear?: Array<TopItem> | null;

    /**
     * @type {Array<TopItem>}
     * @memberof GetSalesDashboardReadModel
     */
    top3CustomersLast12Month?: Array<TopItem> | null;

    /**
     * @type {number}
     * @memberof GetSalesDashboardReadModel
     */
    salesVolumeThisYear?: number;

    /**
     * @type {number}
     * @memberof GetSalesDashboardReadModel
     */
    salesVolumeLastYear?: number;

    /**
     * @type {number}
     * @memberof GetSalesDashboardReadModel
     */
    salesVolumeLast12Month?: number;

    /**
     * @type {number}
     * @memberof GetSalesDashboardReadModel
     */
    salesVolumeLast24Month?: number;

    /**
     * @type {number}
     * @memberof GetSalesDashboardReadModel
     */
    salesVolumeLast36Month?: number;

    /**
     * @type {number}
     * @memberof GetSalesDashboardReadModel
     */
    totalSalesVolume?: number;
}
