/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InvoiceDTO } from './invoice-dto';
 /**
 * 
 *
 * @export
 * @interface InvoiceDTOResult
 */
export interface InvoiceDTOResult {

    /**
     * @type {boolean}
     * @memberof InvoiceDTOResult
     */
    isSuccess?: boolean;

    /**
     * @type {boolean}
     * @memberof InvoiceDTOResult
     */
    isFailure?: boolean;

    /**
     * @type {Error}
     * @memberof InvoiceDTOResult
     */
    error?: Error;

    /**
     * @type {InvoiceDTO}
     * @memberof InvoiceDTOResult
     */
    value?: InvoiceDTO;
}
