/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OfferId } from './offer-id';
import { OfferItemId } from './offer-item-id';
import { ProductId } from './product-id';
import { Quantity } from './quantity';
 /**
 * 
 *
 * @export
 * @interface OfferItemDTO
 */
export interface OfferItemDTO {

    /**
     * @type {OfferItemId}
     * @memberof OfferItemDTO
     */
    id?: OfferItemId;

    /**
     * @type {OfferId}
     * @memberof OfferItemDTO
     */
    offerId?: OfferId;

    /**
     * @type {number}
     * @memberof OfferItemDTO
     */
    position?: number;

    /**
     * @type {string}
     * @memberof OfferItemDTO
     */
    details?: string | null;

    /**
     * @type {Quantity}
     * @memberof OfferItemDTO
     */
    quantity?: Quantity;

    /**
     * @type {number}
     * @memberof OfferItemDTO
     */
    unitPrice?: number;

    /**
     * @type {number}
     * @memberof OfferItemDTO
     */
    totalPrice?: number;

    /**
     * @type {ProductId}
     * @memberof OfferItemDTO
     */
    productId?: ProductId;

    /**
     * @type {string}
     * @memberof OfferItemDTO
     */
    displayName?: string | null;
}
