/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InvoiceId } from './invoice-id';
import { InvoiceNumber } from './invoice-number';
 /**
 * 
 *
 * @export
 * @interface ReleaseInvoiceCommand
 */
export interface ReleaseInvoiceCommand {

    /**
     * @type {InvoiceId}
     * @memberof ReleaseInvoiceCommand
     */
    id: InvoiceId;

    /**
     * @type {InvoiceNumber}
     * @memberof ReleaseInvoiceCommand
     */
    number?: InvoiceNumber;

    /**
     * @type {Date}
     * @memberof ReleaseInvoiceCommand
     */
    releasedOn?: Date;
}
