/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Serie
 */
export interface Serie {

    /**
     * @type {string}
     * @memberof Serie
     */
    label?: string | null;

    /**
     * @type {string}
     * @memberof Serie
     */
    key?: string | null;

    /**
     * @type {string}
     * @memberof Serie
     */
    group?: string | null;

    /**
     * @type {Array<number>}
     * @memberof Serie
     */
    values?: Array<number> | null;
}
