/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Unit
 */
export interface Unit {

    /**
     * @type {string}
     * @memberof Unit
     */
    value?: string | null;

    /**
     * @type {string}
     * @memberof Unit
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof Unit
     */
    shortName?: string | null;
}
