/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CatalogItemId } from './catalog-item-id';
import { InvoiceId } from './invoice-id';
import { InvoiceItemId } from './invoice-item-id';
import { Quantity } from './quantity';
 /**
 * 
 *
 * @export
 * @interface UpdateInvoiceItemCommand
 */
export interface UpdateInvoiceItemCommand {

    /**
     * @type {InvoiceItemId}
     * @memberof UpdateInvoiceItemCommand
     */
    id: InvoiceItemId;

    /**
     * @type {InvoiceId}
     * @memberof UpdateInvoiceItemCommand
     */
    invoiceId: InvoiceId;

    /**
     * @type {string}
     * @memberof UpdateInvoiceItemCommand
     */
    details: string | null;

    /**
     * @type {Quantity}
     * @memberof UpdateInvoiceItemCommand
     */
    quantity: Quantity;

    /**
     * @type {number}
     * @memberof UpdateInvoiceItemCommand
     */
    unitPrice: number;
    
    /**
     * @type {CatalogItemId}
     * @memberof AddInvoiceItemCommand
     */
    catalogItemId?: CatalogItemId;
}
