/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OrderId } from './order-id';
import { OrderReferences } from './order-references';
 /**
 * 
 *
 * @export
 * @interface UpdateReferencesToOrderCommand
 */
export interface UpdateReferencesToOrderCommand {

    /**
     * @type {OrderId}
     * @memberof UpdateReferencesToOrderCommand
     */
    orderId?: OrderId;

    /**
     * @type {OrderReferences}
     * @memberof UpdateReferencesToOrderCommand
     */
    references?: OrderReferences;
}
